# roles/wordpress/tasks/config.yml
# Configures Wordpress
---
- name: httpd content files
  copy: 
    src: index.php
    dest: /var/www/html

- name: httpd content files
  copy: 
    src: search.php
    dest: /var/www/html
  notify: restart httpd

- name: Set SE linux permission httpd_can_network_connect_db
  command: 'setsebool -P httpd_can_network_connect_db 1'

- name: Set SE linux permission httpd_can_network_connect
  command: 'setsebool -P httpd_can_network_connect 1'