# roles/wordpress/tasks/install.yml
---
- name: Ensure httpd and php packages are installed
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ httpd_packages }}"

- name: Start php-fpm
  systemd:
    name: php-fpm
    state: started
    enabled: true

- name: Start httpd
  systemd:
    name: httpd
    state: started
    enabled: true
  #needs modification
