---
rhbase_firewall_allow_services: 
  - mysql

mariadb_bind_address: '192.168.69.17'

mariadb_root_password: 'root'

mariadb_users:
  - name: test
    password: test
    priv: 'test.*:ALL'
    host: '192.168.69.17'

mariadb_databases:
  - name: HA
    init_script: ../files/InitScript.sql

