# host_vars/lampstack.yml
---

rhbase_repositories:
  - epel-release

rhbase_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced
  - tcpdump

rhbase_firewall_allow_services:
  - http
  - https
bertvv.httpd
wordpress_database: wordpress
wordpress_user: wordpressusr
wordpress_password: BulpashCod
