# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_repositories:
  - epel-release

rhbase_install_packages:
  - git
  - tree
  - vim
  - htop
  - wget
  - vim
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  
rhbase_firewall_allow_ports: 
  - 9090/tcp
  - 9100/tcp

fail2ban_loglevel: INFO
fail2ban_logtarget: /var/log/fail2ban.log

fail2ban_ignoreself: "true"
fail2ban_ignoreips: "127.0.0.1/8 ::1"

fail2ban_bantime: 900
fail2ban_findtime: 120
fail2ban_maxretry: 3