# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_repositories:
  - epel-release

rhbase_install_packages:
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  - tree
  - vim-enhanced
  - tcpdump

rhbase_firewall_allow_services:
  - http
  - https
  - mysql

rhbase_firewall_allow_ports: 3306/tcp