# group_vars/all.yml
# Variables visible to all nodes
---
rhbase_repositories:
  - epel-release

rhbase_install_packages:
  - git
  - tree
  - wget
  - tcpdump
  - vim-enhanced
  - bash-completion
  - policycoreutils
  - setroubleshoot-server
  
rhbase_firewall_allow_services:
  - http
  - https
  - mysql

rhbase_firewall_allow_ports: 
  - 3306/tcp
  - 9090/tcp