---
rhbase_repositories:
  - epel-release

rhbase_install_packages:
  - php

rhbase_firewall_allow_services:
  - http
  - https

rhbase_selinux_booleans:
  - httpd_can_network_connect
  - httpd_can_network_connect_db
  - mysql_connect_http

# defaults file for zabbix_server

# The details to connect to the database.
zabbix_server_database_name: zabbix
zabbix_server_database_user: zabbix
zabbix_server_database_password: zabbix

# How to connect to the mysql database, either `socket` or `network`.
zabbix_server_mysql_connection: socket

# When `zabbix_server_mysql_connection` is set to `network` this role needs
# these three extra setting.
# zabbix_server_database_host: localhost

#wordpress_database_host: '192.168.69.17'


#bertvv.httpd
#wordpress_database: wordpress
#wordpress_user: wordpressusr
#wordpress_password: BulpashCod
