# roles/wordpress/handlers/main.yml
---
- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: restart php-fpm
  service:
    name: php-fpm
    state: restarted
