# site.yml
---
- hosts: webservers
  become: true
  roles:
    - bertvv.rh-base
    - wordpress-change


- hosts: database
  become: true
  roles:
    - bertvv.rh-base
    - bertvv-mariadb

# install cockpit monitoring
- hosts: all
  become: true
  tasks:
    - name: Install Cockpit
      package:
        name:
          - cockpit
          - cockpit-dashboard
    - name: Ensure Cockpit is running
      service:
        name: cockpit.socket
        state: started
        enabled: true
    - name: Allow traffic to Cockpit dashboard through the firewall
      firewalld:
        port: 9090/tcp
        state: enabled
        permanent: true



# web install & config
#- hosts: web
#  become: yes

#  tasks:

#  - name: install nginx
#    apt: name=nginx state=installed

# lb install & config
#- hosts: lb
#  become: yes  

#  tasks:

#  - name: install haproxy
#    apt: pkg={{ item }} state=latest
#    with_items:
#    - haproxy

#  - name: enable haproxy
#    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
#    notify: restart haproxy 

#  handlers:

#  - name: restart haproxy
#    service: name=haproxy state=restarted