# site.yml
---
- hosts: webservers
  become: true
  roles:
    - httpd-test

- hosts: db
  become: true
  roles:
    - bertvv.mariadb

- hosts: lb
  become: true
  roles:
    - geerlingguy.haproxy

- hosts: monitor
  become: true

- hosts: all
  become: true
  roles:
    - bertvv.rh-base
