# site.yml
---
- hosts: webservers
  become: true
  roles:
    - httpd-test

- hosts: db
  become: true
  roles:
    - bertvv.mariadb

- hosts: lb
  become: true
  roles:
    - geerlingguy.haproxy

- hosts: monitor
  become: true
#  tasks:
#  - name: set cockpit machines
#    copy:
#      src: ./files/05-mymachine.json 
#      dest: /etc/cockpit/machines.d/
  roles:
#     - role: robertdebock.bootstrap
#    - role: robertdebock.selinux
#    - role: robertdebock.container_docs
    - role: robertdebock.mysql
      mysql_databases:
        - name: zabbix
          encoding: utf8
          collation: utf8_bin
      mysql_users:
        - name: zabbix
          password: zabbix
          priv: "zabbix.*:ALL"
    - role: robertdebock.zabbix_repository
    - role: robertdebock.core_dependencies
    - role: robertdebock.zabbix_server
    - role: robertdebock.zabbix_web

- hosts: all
  become: true
  roles:
    - bertvv.rh-base
  tasks:  
  - name: install Cockpit
    package:
      name:
        - cockpit
        - cockpit-dashboard
  - name: Ensure Cockpit is running
    service:
      name: cockpit.socket
      state: started
      enabled: true