# site.yml
---
- hosts: webservers
  become: true
  roles:
    - httpd-test
    - cloudalchemy.node-exporter


- hosts: db
  become: true
  roles:
    - bertvv.mariadb
    - cloudalchemy.node-exporter


- hosts: lb
  become: true
  roles:
    - geerlingguy.haproxy
    - cloudalchemy.node-exporter

- hosts: monitor
  become: true
  roles: 
    - cloudalchemy.prometheus
    - cloudalchemy.grafana
  #tasks:
  #- name: set cockpit machines
  #  copy:
  #    src: ./files/05-mymachine.json 
  #    dest: /etc/cockpit/machines.d/

- hosts: all
  become: true
  roles:
    - bertvv.rh-base
    - nbigot.fail2ban
  # tasks:
  #   - name: line insert
  #     lineinfile:
  #       path: /etc/fail2ban/jail.local
  #       line: 'enabled = true'
  #       insertbefore: EOF
  #tasks:
  #  - name: install Cockpit
  #    package:
  #      name:
  #        - cockpit
  #        - cockpit-dashboard
  #  - name: Ensure Cockpit is running
  #    service:
  #      name: cockpit.socket
  #      state: started
  #      enabled: true
  #  - name: Allow traffic to Cockpit dashboard through the firewall
  #    firewalld:
  #      port: 9090/tcp
  #      state: enabled
  #      permanent: true